#!/usr/bin/env bash
# This is bash script that sets up nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart