#!/usr/bin/env bash
# This is bash script that sets up nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Add redirection configuration
REDIRECT_CONFIG='location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }'
# Insert it at line 53
sudo sed -i "53i $REDIRECT_CONFIG" /etc/nginx/sites-available/default

sudo service nginx restart