#!/usr/bin/env bash
# This is bash script that handle a process as a service
pid_f=/var/run/my_process.pid
if [ "$#" -eq 0 ]; then
echo "Usage: manage_my_process {start|stop|restart}"
exit 1
fi
script_pid=$$
case $1 in
"start")
./manage_my_process &
echo "$script_pid" > "$pid_f" &&
echo "manage_my_process started"
;;
"stop")
pkill -f "./manage_my_process" &&
echo "manage_my_process stopped"
;;
"restart")
pkill -f ./"manage_my_process" &&
./manage_my_process &
echo "$script_pid" > "$pid_f" &&
echo "manage_my_process restarted"
;;
esac
