#!/usr/bin/env bash
# This is script diplaying numbers from 1 to 100
# and replaces number with FizzBuzz for num divisable by 3 and 5
# Fizz for num divisable by 3
# Buzz for num divisable by 5
for i in $(seq 1 100); do
if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]; then
echo "FizzBuzz"
elif [ $((i%3)) -eq 0 ]; then
echo "Fizz"
elif [ $((i%5)) -eq 0 ]; then
echo "Buzz"
else
echo "$i"
fi
done
