#!/usr/bin/env bash
# This is bashscript that displays /etc/passwod file content

# Internal Field Separator is empty space
IFS=
 
file_path="/etc/passwd"

while read -r line; do
echo "$line" | cut -d ':' -f 1,3,6
done < "$file_path"
