#!/usr/bin/env bash
# This is bashscript that displays /etc/passwod file content

# Internal Field Separator is empty space
IFS=
 
file_path="/etc/passwd"

while read -r line; do
user=$(cut -d ':' -f 1 <<< "$line")
pass=$(cut -d ':' -f 2 <<< "$line")
uid=$(cut -d ':' -f 3 <<< "$line")
gid=$(cut -d ':' -f 4 <<< "$line")
info=$(cut -d ':' -f 5 <<< "$line")
dir=$(cut -d ':' -f 6 <<< "$line")
shell=$(cut -d ':' -f 7 <<< "$line")
echo "The user $user is part of the $gid gang, lives in $dir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < "$file_path"
