#!/usr/bin/env bash
# Run nginx as nginx user

# Change nginx user in nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Change mode of nginx.conf
chmod 644 /etc/nginx/nginx.conf
# Kill apache2
pkill apache2
# Restart nginx
sudo -u nginx service nginx start
