#!/usr/bin/env bash
# Run nginx as nginx user

# Change nginx user in nginx.conf
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
# Listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
